//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTicketsOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passage()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int id { get; set; }
        public Nullable<int> Liner_id { get; set; }
        public int PassageNumber { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Arrival { get; set; }
        public Nullable<int> Crew_id { get; set; }
    
        public virtual Crew Crew { get; set; }
        public virtual Liner Liner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
